[package]
name = "themis-tracer"
# TODO Add version constraints before incrementing version
version = "0.1.0"
authors = [
"Thane Thomson <thane@informal.systems>",
"Shon Feder <shon@informal.systems>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#
[features]
# Treat warnings as a build error.
strict = []

[lib]
name = "tracer"
path = "src/lib.rs"

[[bin]]
name = "themis-tracer"
doc = false

[dependencies]
csv = "*"
failure = "*"
pandoc_ast = "*"
log = "*"
peg = "*"
simple_logger = "*"
structopt = "*"
serde = { version = "*", features = ["derive"] }
# serde_dhall = "*"
serde_json = "*"

[dev-dependencies]
assert_cmd = "*"
glob = "*"
textwrap = "*"
tempfile = "*"
