[package]
name = "themis-tracer"
version = "0.1.0"
authors = ["Thane Thomson <thane@informal.systems>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "themis-tracer"
doc = false

[dependencies]
failure = "^0.1.8"
pandoc_ast = "^0.7.2"
log = "^0.4.8"
peg = "^0.6.2"
simple_logger = "^1.6.0"
structopt = "^0.3.14"
serde = "^1.0.106"
serde_dhall = "^0.5.2"
serde_json = "^1.0.53"

[dev-dependencies]
textwrap = "^0.11.0"
tempfile = "^3.1.0"
