[package]
name = "themis-tracer"
version = "0.1.0"
authors = [
"Thane Thomson <thane@informal.systems>",
"Shon Feder <shon@informal.systems>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#
[features]
# Treat warnings as a build error.
strict = []

[[bin]]
name = "themis-tracer"
doc = false

[dependencies]
failure = "*"
pandoc_ast = "*"
log = "*"
peg = "*"
simple_logger = "*"
structopt = "*"
serde = "*"
serde_dhall = "*"
serde_json = "*"

[dev-dependencies]
assert_cmd = "*"
glob = "*"
racer = "*"
rust-analyzer = "*"
rustfmt-nightly = "*"
cargo-check = "*"
textwrap = "^0.11.0"
tempfile = "^3.1.0"
